version: "3.3"
services:
  wakmusic-bot:
    image: wakmusic-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./logs:/usr/src/app/logs
    env_file:
      - .env
