version: '3.3'
services:
  wakmusic-bot:
    image: eatcocoa/wakmusic-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./logs:/usr/src/app/logs
      - /home/ubuntu/wakmusic-lyrics/static:/home/ubuntu/wakmusic-lyrics/static
    env_file:
      - .env
